### ISSUE TITLE
improved typing for litellm 

### ISSUE THREAD

**Issue by ghost** [Znunu/aichatlib#2]
> They are very thin wrappers with an overreliance on dicts for everything

Hey @Znunu we're trying to improve litellm's typing, to catch these issues. Any feedback on specific changes we can make to improve here?

**Comment by Znunu** [comment]
Hey again! I'm more than happy to provide feedback, but for another time, please ping me over there instead. I don't get why you're pinging me here...
>  Any feedback on specific changes we can make to improve here?

It's hard for me to say, you know better than me. More documentation I think? If they are meant to be used directly (and not just "private" classes), then that is not documented very well. However from my understanding, litellm is meant to be an easy replacement for code already using the openAI library. I am going for something else with my own code here, a more model agnostic and consistent library!
